config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'snippets#following'

  get '/callback', to: "pages#callback"

  resources :users do
    get 'following','followers', on: :member
  end

  resources :users, only: [:show]
  resources :tracks, only: [:index, :new, :create, :show, :destroy]
  resources :snippets, only: [:index, :show, :create, :destroy]

  post "tracks/upload", :as => :upload

  post "/share", to: 'facebook#post_to_facebook'

  resources :votes, only: [:create]
  resources :follows, only: [:create, :destroy]
end

app/models/track.rb
class Track < ActiveRecord::Base
  scope :most_recent, -> { order(created_at: :desc) }

  has_many :snippets
  belongs_to :user
  has_many :votes, as: :votable

  def string_duration
    total_seconds = self.duration.to_f/1000
    minutes = (total_seconds/60).to_i
    seconds = total_seconds.to_i % minutes
    "#{minutes} m #{seconds} s"
  end

  def score
    self.votes.size
  end

  def voters
    self.votes.includes(:user).map(&:user)
  end

  def already_voted?(user)
    self.voters.include?(user)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def index
    @tracks = Track.all
  end

  def new
    if current_user
      @track = Track.new
    else
      redirect_to root_path
    end
  end

  def create
    @tracks = []
    if request.xhr?
      params[:tracks].each do |key, track_data|
        track = current_user.tracks.find_or_create_by(
          source_id: track_data['id'],
          permalink_url: track_data['permalink_url'],
          artwork_url: track_data['artwork_url'],
          description: track_data['description'],
          duration: track_data['duration'],
          waveform_url: track_data['waveform_url'],
          bpm: track_data['bpm'],
          artist: track_data['user']['username'],
          title: track_data['title']
        )
        next unless track.save
        @tracks << track
      end
      render @tracks, layout: false
    else
      @track = current_user.tracks.new(track_params)
      if @track.save
        redirect_to track_path @track
      else
        redirect_to new_track_path
      end
    end
  end

  def show
    @track = Track.find params[:id]
  end

  private
    def track_params
      params.require(:track).permit(:source_id, :permalink_url, :artwork_url, :description, :duration, :waveform_url, :bpm, :title, :artist)
    end

end

app/views/tracks/_form.html.erb
<ul>
  <%= form_for @track do |f| %>
    <%f.label :soundcloud_track_id %>
    <%= f.text_field :soundcloud_track_id, :placeholder => "Enter your soundcloud url"%>
  <br>
  <br>
    <%= f.submit "Create Your Track" %>
  <% end %>
</ul>

app/views/tracks/_show.html.erb
<div class='row track' data-source-id="<%= track.source_id %>" data-track-id="<%= track.id %>">
  <ul class="small-block-grid-3">
    <li><img src="<%= track.artwork_url %>"/></li>
    <li>Description: <%= track.description %></li>
    <li>Length: <%= track.string_duration %></li>
    <li>Posted By: <%= track.user.first_name %></li>
  </ul>
</div>

app/views/tracks/_track.html.erb
<div class="row collapse partial track" data-source-id="<%= track.source_id %>" data-track-id="<%= track.id %>"
data-track-desc="<%= track.description %>"
data-track-len="<%= track.string_duration %>">
  <div class="small-2 columns padded-column">
    <% if !track.artwork_url.empty? %>
      <img class="album_art" src="<%= track.artwork_url %>">
    <% else %>
      <img class="album_art" src="<%= asset_path('logo.png') %>">
    <% end %>
  </div>

  <div class="small-offset-1 small-6 columns padded-column">
    <span>Artist: </span><%= link_to track.artist, user_path(id: track.user_id), class: "link_artist" %><br>
    <span>Length: </span> <%= track.string_duration %><br>
    <span>Title: </span><%= link_to track.title, track_path(id: track.id), class: "link_artist" %>
  </div>
  <div class="small-2 end columns padded-column">
    <%= link_to image_tag('share.png', :class => 'track-share track-icon'), "#", id: track.id, class: "item share pulse" %>

    <%= link_to image_tag('like.png', :class => 'track-like track-icon'), '#', id: track.id, class: "item like pulse"  %>
    <div class='score' id='<%= track.id %>'><%= track.score %></div>
  </div>
</div>

app/views/tracks/_updated_show.html.erb
<% tracks.each do |track| %>
  <%= render partial: "tracks/show", locals: {track: track} %>
<% end %>

app/views/tracks/index.html.erb
<div class="user-tracks">
  <h2>Tracks</h2>
    <% @tracks.each do |track| %>
      <%= render :partial => 'tracks/track', :locals => {:track => track} %>
    <% end %>
</div>

app/views/tracks/show.html.erb
<div class="user-tracks">
  <div class="row track" data-source-id="<%= @track.source_id %>" data-track-id="<%= @track.id %>">
    <div class="small-2 columns padded-column">
      <img src="<%= @track.artwork_url %>"/></li>
    </div>
    <div class="small-offset-1 small-8 columns padded-column">
      <p><%= @track.title %></p>
      <p> By: <%= @track.artist %> </p>
      <p>About this Track:<%= @track.description %></p>
      <p>Length: <%= @track.duration %></p>
    </div>
  </div>
  <div class="row">
    <p>Posted By: <%= User.find(@track.user_id).first_name %></p>
  </div>
</div>
<p> Snippets made from this track </p>
  <div class='user-snippets'>
      <% @track.snippets.most_recent.each do |snippet| %>
      <%= render :partial => 'snippets/snippet', :locals => {:snippet => snippet} %>
      <% end %>
  </div>

app/views/tracks/upload.html.erb
<h2>Upload a new MP3:</h2>
<%= form_tag upload_path, :method => "post", :multipart => true do %>
    <%= file_field_tag "mp3file" %>
    <%= submit_tag "Upload" %>
<% end %>