config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'snippets#following'

  get '/callback', to: "pages#callback"

  resources :users do
    get 'following','followers', on: :member
  end

  resources :users, only: [:show]
  resources :tracks, only: [:index, :new, :create, :show, :destroy]
  resources :snippets, only: [:index, :show, :create, :destroy]

  post "tracks/upload", :as => :upload

  post "/share", to: 'facebook#post_to_facebook'

  resources :votes, only: [:create]
  resources :follows, only: [:create, :destroy]
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  scope :most_recent, -> { order(created_at: :desc) }
  
  belongs_to :track
  belongs_to :user

  has_many :votes, as: :votable

  validates :user, presence: true
  validates :start_time, :end_time, presence: true

  def original_creator
    self.track.user
  end

  def score
    self.votes.size
  end

  def voters
    self.votes.includes(:user).map(&:user)
  end

  def already_voted?(user)
    self.voters.include?(user)
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  include FacebookHelper
  before_action :authenticate_user!, only: [:create, :following]

  def index
    @snippets = Snippet.all
  end

  def following
    @snippets = []
    current_user.following.each do |followed|
      @snippets.push(followed.snippets.most_recent.limit(3))
    end
    @snippets.flatten!
  end

  def show
    @snippet = Snippet.find(params[:id])
  end

  def create
    @user = current_user
    @snippet = @user.snippets.new(snippet_params)
    if Track.find(params[:snippet][:track_id]).snippets << @snippet
      share({token: current_user.token, item: @snippet}) if Rails.env.production?
      render nothing: true
    else
      redirect_to :back
    end
  end

  def destroy
    snippet = Snippet.find(params[:id])
    snippet.destroy
    redirect_to root_path
  end

  private
    def snippet_params
      params.require(:snippet).permit(:track_id, :start_time, :end_time)
    end
end

app/views/snippets/_snippet.html.erb
<div class="row collapse partial snippet" data-source-id="<%= snippet.track.source_id %>" data-start-time="<%= snippet.start_time %>" data-end-time="<%= snippet.end_time %>" >
  <div class="small-2 columns padded-column">
    <% if !snippet.track.artwork_url.empty? %>
      <img class="album_art" src="<%= snippet.track.artwork_url %>">
    <% else %>
      <img class="album_art" src="<%= asset_path('logo.png') %>">
    <% end %>
  </div>

  <div class="small-offset-1 small-6 columns padded-column">
    <% if !snippet.track.artwork_url.empty? %>
      <span>Title: </span><%= link_to snippet.track.title, track_path(id: snippet.track.id), class: "link_artist" %>
    <% else %>
      Track Title:
    <% end %><br>

    <% if !snippet.track.artist.empty? %>
      <span>Artist: </span><%= link_to snippet.track.artist, user_path(id: snippet.track.user_id), class: "link_artist" %>
    <% else %>
      <span>Artist: </span>
    <% end %><br>

    <span>Created By:</span> <%= snippet.original_creator.full_name %>
  </div>

  <div class="small-2 end columns padded-column">
    <%= link_to image_tag('share.png', :class => 'track-icon'), "#", id: snippet.id, class: "item share pulse" %>

    <%= link_to image_tag('like.png', :class => 'snippet-like track-icon'), "#", id: snippet.id, class: "item like pulse" %>
    <div class='score' id='<%= snippet.id %>'><%= snippet.score %></div>
  </div>
</div>

app/views/snippets/_soundplayer.html.erb
# delete
<div class="row">
  <div class="large-12 columns">
  <div class="playerlist-item">
  <div class="activity">
    <div class="soundstream-media-content">
    </div>
    <div class="soundstream-header">
      <div id="sound-play-button">
      </div>
      <div id="sound-pause-button">
      </div>
      <div id="sound-rewind-button">
      </div>
      <div id="sound-fastforward-button">
      </div>
      <div id="soundstream-track-player">
        <span style="width: 25%"></span>
      </div>
      <div class="sound-title">
        Pesos
      </div>
      <div class="sound-artist">
        ASAP
      </div>
    </div>
    <div class="soundstream-button-actions">
      <div id="favorite-button">
      </div>
      <div id="share-button">
      </div>
      <div id="repost-button">
      </div>
    </div>
  </div>
</div>
</div>

app/views/snippets/following.html.erb
<div class='user-snippets'>
  <h2> <%= current_user.first_name %>'s Feed </h2>
   <% @snippets.each do |snippet| %>
    <%= render :partial => 'snippets/snippet', :locals => {:snippet => snippet} %>
   <% end %>
</div>

app/views/snippets/index.html.erb
<div class='user-snippets'>
  <h2> Snippets </h2>
   <% @snippets.most_recent.each do |snippet| %>
    <%= render :partial => 'snippets/snippet', :locals => {:snippet => snippet} %>
   <% end %>
</div>

app/views/snippets/show.html.erb
<div class="user-snippets">
  <div class="row snippet" data-source-id="<%= @snippet.track.source_id %>" data-snippet-id="<%= @snippet.id %>">
    <div class="small-2 columns padded-column">
      <img src="<%= @snippet.track.artwork_url %>"/></li>
    </div>
    <div class="small-offset-1 small-8 columns padded-column">
      <span>A Snippet by <%= @snippet.user.first_name %></span>
      <p><%= @snippet.track.title %></p>
      <p>By: <%= @snippet.track.artist %> </p>
      <p>About this Track:<%= @snippet.track.description %></p>
      <p>Length: <%= @snippet.track.string_duration %></p>
    </div>
  </div>
</div>
<p> Snipped From: </p>
<div class='user-tracks'>
  <%= render :partial => 'tracks/track', :locals => {:track => @snippet.track} %>
</div>