config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'snippets#following'

  get '/callback', to: "pages#callback"

  resources :users do
    get 'following','followers', on: :member
  end

  resources :users, only: [:show]
  resources :tracks, only: [:index, :new, :create, :show, :destroy]
  resources :snippets, only: [:index, :show, :create, :destroy]

  post "tracks/upload", :as => :upload

  post "/share", to: 'facebook#post_to_facebook'

  resources :votes, only: [:create]
  resources :follows, only: [:create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :votes
  devise :database_authenticatable, :rememberable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :tracks
  has_many :snippets

  has_many :follows, :foreign_key => "follower_id"
  has_many :following, :through => :follows, :source => :followed

  has_many :reverse_follows, :foreign_key => "followed_id",
                             :class_name => "Follow"
  has_many :followers, :through => :reverse_follows, :source => :follower

  before_create :remember

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.first_name = auth['info']['first_name']
      user.last_name = auth['info']['last_name']
      user.email = auth['info']['email']
      user.profile_img_url = auth['info']['image']
      user.token = auth['credentials']['token']
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def link_soundcloud_account(auth)
    self.sound_cloud_id = auth['id']
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def is_following?(followed)
    follows.find_by_followed_id(followed)
  end

  def follow(followed)
    follows.create(:followed_id => followed.id)
  end

  def unfollow(followed)
    follows.find_by_followed_id(followed).destroy
  end

  def remember
    self.remember_created_at = DateTime.now
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end

  end
end

app/controllers/users/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def following
    @user = User.find(params[:id])
    render 'follow_show'
  end

  def followers
    @user = User.find(params[:id])
    render 'follower_show'
  end


end

app/views/users/_follow.html.erb
<%= form_for current_user.follows.new(:followed_id => @user.id),
                                       remote: true)  do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <button><%= f.submit "Follow "%></button>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user && @user.id != current_user.id%>
    <div id="follow_form">
    <% if current_user.is_following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.follows.find_by_followed_id(@user),
                             :html => { :method => :delete },
                              :remote => true  do |f| %>
  <button><%= f.submit "Unfollow" %></button>
<% end %>

app/views/users/follow_show.html.erb
<ul>
  <h2>Following</h2>

  <div class="row collapse">
  <div class="following-column">
    <% @user.following.each do |user| %>
    <span>
      <div class="following-picture">
        <%= link_to image_tag(user.profile_img_url), user_path(user) %>
      </div>
      <div class="following-name">
        <%= link_to "#{user.full_name}", user_path(user) %>
      </div>
      <div class="following-audio">
        <span><%= user.tracks.count %> Tracks</span>
        <span><%= user.snippets.count %> Snippets</span>
      </div>
    </span>
    <% end %>
      </div>
  </div>
</div>
</ul>

app/views/users/follower_show.html.erb
<ul>
  <h2>Followers</h2>

  <div class="row collapse">
  <div class="followers-column">
    <% @user.followers.each do |user| %>
      <span>
        <div class="followers-picture">
          <%= link_to image_tag(user.profile_img_url), user_path(user) %>
        </div>
        <div class="followers-name">
        <%= link_to "#{user.full_name}", user_path(user) %>
      </div>
      <div class="followers-audio">
        <p><span><%= user.tracks.count %> Tracks</span>
        <span><%= user.snippets.count %> Snippets</span></p>
      </div>
    </span>
    <% end %>
  </div>
</div>
</div>
</ul>

app/views/users/index.html.erb
<%= link_to("signin", user_session_path) %>

app/views/users/login.html.erb
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

app/views/users/show.html.erb
<div class="row">

</div>

<ul class="small-block-grid-3">
  <li><%= image_tag (@user.profile_img_url), :class => "profile_image" %></li>
  <% if @user == current_user %>
    <li class="connect"><%= render :partial => 'soundcloud/connect' %></li>
  <% end %>
  <% if @user != current_user %>
    <% if current_user %>
      <% if current_user.is_following?(@user) %>
        <li><img class="unfollow" src="<%= asset_path('follow.png') %>"  data-user-id="<%= @user.id %>"></li>
      <% else %>
        <li><img class="follow" src="<%= asset_path('follow.png') %>"  data-user-id="<%= @user.id %>"></li>
      <% end %>
    <% else %>
      <li>you're not logged in</li>
    <% end %>
  <% end %>
</ul><br><br>

<ul class="small-block-grid-3 me">
  <li><%= @user.full_name %></li>
  <li>
    <div class="follow-count"><%= @user.followers.count %></div>
    <%= link_to "Followers", followers_user_path(@user) %>
  </li>

  <li>
    <%= @user.following.count %>
    <%= link_to "Following", following_user_path(@user) %>
  <li>
</ul><br><br>

<h4> Recent Tracks </h4>
<div class='user-tracks'>
  <% @user.tracks.most_recent.each do |track| %>
    <%= render :partial => 'tracks/track', :locals => {:track => track} %>
  <% end %>
</div>

<h4> Recent Snippets </h4>
<div class='user-snippets'>
  <% @user.snippets.most_recent.each do |snippet| %>
    <%= render :partial => 'snippets/snippet', :locals => {:snippet => snippet} %>
  <% end %>
</div>