config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'snippets#following'

  get '/callback', to: "pages#callback"

  resources :users do
    get 'following','followers', on: :member
  end

  resources :users, only: [:show]
  resources :tracks, only: [:index, :new, :create, :show, :destroy]
  resources :snippets, only: [:index, :show, :create, :destroy]

  post "tracks/upload", :as => :upload

  post "/share", to: 'facebook#post_to_facebook'

  resources :votes, only: [:create]
  resources :follows, only: [:create, :destroy]
end

app/views/layouts/_header.html.erb
<div data-magellan-expedition="fixed">
  <dl class="sub-nav">
    <dd data-magellan-arrival="build"><a href="#build">Persistent Music Widget</a></dd>
    <dd data-magellan-arrival="js"><a href="#js">User profile image</a></dd>
  </dl>
</div>

app/views/layouts/_navigation_side.html.erb
<div class="icon-bar vertical five-up">

  <%= link_to image_tag('home.png'), root_path, class: "item home first" %>
  <%= link_to image_tag('orange_home.png'), root_path, class: "item home first orange" %>

  <%= link_to image_tag('track.png'), tracks_path, class: "item home second" %>
  <%= link_to image_tag('orange_track.png'), tracks_path, class: "item home second orange" %>

  <%= link_to image_tag('snippet.png'), snippets_path, class: "item home third" %>
  <%= link_to image_tag('orange_snippet.png'), snippets_path, class: "item home third orange" %>

  <%= link_to image_tag('me.png'), user_path(id: current_user.id), class: "item home fourth" %>
  <%= link_to image_tag('orange_me.png'), user_path(id: current_user.id), class: "item home fourth orange" %>


  <%= link_to image_tag('logout.png'), destroy_user_session_path, method: "delete", class: "item home fifth" %>
  <%= link_to image_tag('orange_logout.png'), destroy_user_session_path, method: "delete", class: "item home fifth orange" %>



</div>

app/views/layouts/_navigation_top.html.erb
<div class="contain-to-grid fixed">
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Home", root_path %></a></h1>
      </li>
    </ul>
    <section class="top-bar-section">
      <ul class="left">
        <li class="divider"></li>
        <li><%= link_to "Tracks", tracks_path, :class=>"track_link"%></li>
        <li class="divider"></li>
        <li><%= link_to "Snippets", snippets_path %></li>
        <li class="divider"></li>
        <li><%= link_to "My Profile", user_path(current_user.id) %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_player.html.erb
<div class="widget">
  <div id="player">
    <img class="O" src="<%= asset_path('O.png') %>" >
  </div>

<img id="soundplayer-widget-picture" src="<%= asset_path('sg.png') %>">

<img class="icon play" src="<%= asset_path('play.png') %>" >
<img class="icon stop" src="<%= asset_path('stop.png') %>" >
<img class="icon next" src="<%= asset_path('next.png') %>" >
<img class="icon previous" src="<%= asset_path('previous.png') %>" >
<img class="icon snip" id="snip" src="<%= asset_path('snip.png') %>" >

<img class="icon play yellow" src="<%= asset_path('play_yellow.png') %>" >
<img class="icon stop yellow" src="<%= asset_path('stop_yellow.png') %>" >
<img class="icon next yellow" src="<%= asset_path('next_yellow.png') %>" >
<img class="icon previous yellow" src="<%= asset_path('previous_yellow.png') %>" >
<img class="icon snip yellow" id="snip" src="<%= asset_path('snip_yellow.png') %>" >
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <%= render partial: "meta/facebook_meta_tags" %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <title>Stereogram</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'http://connect.soundcloud.com/sdk.js'%>
    <%= csrf_meta_tags %>
  </head>


  <body>
    <div class="player">
      <%= render 'layouts/player' %>
    </div>
    <div class="small-2 columns" id="left">
      <%= render 'layouts/navigation_side' %>
    </div>
    <div class="small-5 columns" id="center"></div>
    <div class="small-5 columns" id="right">
      <%= yield %>
    </div>

  <%= javascript_include_tag "application" %>
</body>
</html>